services:
  krakend:
      build:
        context: infra/krakend
      container_name: krakend
      ports:
        - "8080:8080"
        - "8090:8090"
      networks:
        - tech-talent

  tech_talent_formation:
    build:
      context: code/frontend/Formation
    container_name: tech_talent_formation
    ports:
      - "8084:80"
    networks:
      - tech-talent

  tech_talent_auth:
    build:
      context: code/frontend/Authentification
    container_name: tech_talent_auth
    ports:
      - "8083:80"
    networks:
      - tech-talent

  tech_talent_app:
    build:
      context: code/frontend/App
    container_name: tech_talent_app
    ports:
      - "8082:80"
    networks:
      - tech-talent

  tech_talent:
    build:
      context: ./infra/reverse_proxy
    container_name: tech_talent
    ports:
      - "443:443"
      - "80:80"
    networks:
      tech-talent:
        ipv4_address: 172.20.0.100

  authentification:
    build:
      context: code/backend/Authentification
    container_name: authentification
    ports:
      - "7070:7070"
    networks:
      - tech-talent
    environment:
      - MONGO_URI=mongodb://db_auth:27016/db_auth
      - KeyAccess=TechTalentAuthAcces
      - KeyRefresh=TechTalentAuthRefresh

  db_auth:
    image: mongo:latest
    container_name: db_auth
    ports:
      - "27016:27017"
    networks:
      - tech-talent
    volumes:
      - mongo_data_auth:/data/db

  user:
    build:
      context: code/backend/User
    container_name: user
    ports:
      - "7071:7071"
    networks:
      - tech-talent
    environment:
      - MONGO_URI=mongodb://db_user:27015/db_user

  db_user:
    image: mongo:latest
    container_name: db_user
    ports:
      - "27015:27017"
    networks:
      - tech-talent
    volumes:
      - mongo_data_user:/data/db

networks:
  tech-talent:
    name: tech-talent
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongo_data_auth: {}
  mongo_data_user: {}

