version: '3'

includes:
  dev : ./config/taskfiles/dev.yml
  prod: ./config/taskfiles/prod.yml

tasks:
  config:
    desc: Launch the different types of script for configuration
    cmds:
      - "./script/config/Host.sh set"

  uninstall:
    desc: Launch the different types of script uninstall all configuration project
    cmds:
      - "./script/config/Host.sh remove"

  default:
    cmds:
      - task config
      - task prod

