version: '3'

tasks:
  start:
    desc: Start Deploy Project
    cmds:
      - docker-compose -f ./docker-compose.yml up -d

  build:
    desc: Build Deploy Project
    cmds:
      - docker-compose -f ./docker-compose.yml build

  down:
    desc: Remove the docker-compose
    cmds:
      - docker-compose -f ./docker-compose.yml down

  reload:
    desc: Reload Deploy Project
    cmds:
      - task: down
      - task: build
      - task: start

  rebuild:
    desc: Completely remove and rebuild Deploy Project
    cmds:
      - task: down
      - docker system prune -a -f
      - task: build
      - task: start

  default:
    desc: Default task to build Deploy Project
    cmds:
      - task: rebuild
